// <auto-generated />
using System;
using Intelligent_Retail2.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Intelligent_Retail2.Migrations
{
    [DbContext(typeof(Intelligent_Retail2Context))]
    partial class Intelligent_Retail2ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Intelligent_Retail2.Models.AdminUser", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AdminPassword");

                    b.Property<string>("AdminUserEmail")
                        .IsRequired();

                    b.Property<string>("AdminUserName")
                        .IsRequired();

                    b.Property<string>("AdminUserNumber")
                        .IsRequired();

                    b.Property<string>("AdminUserPhone")
                        .IsRequired();

                    b.Property<string>("AdminUserRole");

                    b.HasKey("ID");

                    b.ToTable("AdminUser");
                });

            modelBuilder.Entity("Intelligent_Retail2.Models.BrandCategory", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("BrandInfo");

                    b.Property<string>("BrandName");

                    b.HasKey("ID");

                    b.ToTable("BrandCategory");
                });

            modelBuilder.Entity("Intelligent_Retail2.Models.CommodityManage", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("BrandID");

                    b.Property<string>("CategoryID");

                    b.Property<string>("ProductImage");

                    b.Property<string>("ProductName");

                    b.Property<string>("ProductPrice");

                    b.Property<int>("ProductSale");

                    b.Property<int>("ProductStock");

                    b.HasKey("ID");

                    b.ToTable("CommodityManage");
                });

            modelBuilder.Entity("Intelligent_Retail2.Models.DeviceManage", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DeviceAddress")
                        .IsRequired();

                    b.Property<string>("DeviceCity")
                        .IsRequired();

                    b.Property<string>("DeviceNumber")
                        .IsRequired();

                    b.Property<string>("DeviceProductKey")
                        .IsRequired();

                    b.Property<string>("DeviceProvince")
                        .IsRequired();

                    b.Property<string>("DeviceSecret")
                        .IsRequired();

                    b.Property<DateTime>("DeviceSetDay");

                    b.HasKey("ID");

                    b.ToTable("DeviceManage");
                });

            modelBuilder.Entity("Intelligent_Retail2.Models.DeviceProduct", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("DeviceID");

                    b.Property<int>("DeviceProductSale");

                    b.Property<int>("DeviceProductStock");

                    b.Property<string>("ProductID");

                    b.HasKey("ID");

                    b.ToTable("DeviceProduct");
                });

            modelBuilder.Entity("Intelligent_Retail2.Models.ProductCategory", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CategoryInfo");

                    b.Property<string>("CategoryName");

                    b.HasKey("ID");

                    b.ToTable("ProductCategory");
                });

            modelBuilder.Entity("Intelligent_Retail2.Models.User", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("UserGender");

                    b.Property<string>("UserNickName");

                    b.Property<string>("UserOpenID");

                    b.Property<string>("UserPhone");

                    b.HasKey("ID");

                    b.ToTable("User");
                });
#pragma warning restore 612, 618
        }
    }
}
